version: '2'
services:
  db:
    image: "postgres"
    environment:
        - POSTGRES_USER=goonyc-admin
        - POSTGRES_PASSWORD=spacecat1
    ports:
        - "5432:5432"
  web:
    build: docker build -t docker-sinatra:latest .
    image: docker-sinatra:latest
    ports:
      - "4567:80"
    links:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=getoutofnyc
      - DATABASE_USER=getoutofnyc
      - DATABASE_PASSWORD=spacecat1