development:
  adapter: postgresql
  encoding: unicode
  pool: 2
  database: <%= ENV['DATABASE_NAME'] || 'getoutofnyc' %>
  username: <%= ENV['DATABASE_USER'] || 'goonyc-admin' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'spacecat1' %>

production:
  adapter: postgresql
  encoding: unicode
  database: getoutofnyc
  username: getoutofnyc
  password: spacecat1
  host: aa1wnfoa5vacmfw.c8plrwqkyfst.us-east-1.rds.amazonaws.com
  port: 5432