development:
  adapter: postgresql
  encoding: unicode
  database: goonyc_dev
  pool: 2
  username: goonyc-admin
  password: spacecat1

production:
  adapter: postgresql
  encoding: unicode
  database: goonyc_prod
  pool: 2
  username: goonyc-admin
  password: spacecat1