development:
  adapter: postgresql
  encoding: unicode
  database: goonyc_dev
  pool: 2
  username: goonyc-admin
  password: spacecat1

production:
  adapter: postgresql
  encoding: unicode
  database: getoutofnyc
  username: getoutofnyc
  password: spacecat1
  host: aa1wnfoa5vacmfw.c8plrwqkyfst.us-east-1.rds.amazonaws.com
  port: 5432