development:
  adapter: postgresql
  encoding: unicode
  database: goonyc_dev
  pool: 2
  username: your_username
  password: your_password

production:
  adapter: postgresql
  encoding: unicode
  database: goonyc_prod
  pool: 2
  username: goonyc-admin
  password: